# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20170601_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='title',
            new_name='item_title',
        ),
    ]
