# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-23 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20170822_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='children',
        ),
        migrations.RemoveField(
            model_name='list',
            name='completed',
        ),
        migrations.AlterField(
            model_name='list',
            name='item_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
