# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-28 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_auto_20170823_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='_list_children_+', to='lists.List'),
        ),
    ]
