# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-28 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_auto_20171128_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='children',
        ),
        migrations.AddField(
            model_name='list',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='children', to='lists.List'),
        ),
    ]
