# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-06 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_auto_20171128_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, related_name='parent', to='lists.List'),
        ),
    ]
