# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-13 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_auto_20171207_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='order_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
