# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-13 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0011_list_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='sloop',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
